baseURL = 'https://mattkjones.net'
languageCode = 'en-us'
title = 'matt jones'
theme = 'hyde'    

[markup.goldmark.renderer] 
    unsafe= true

[Params]
    description = 'Developing web, API integration, and automation. Based in Atlanta, GA.'
    themeColor = 'theme-base-08'
    copyright = 'mail@mattkjones.net'
    contactFormId = 'xpzbkblo'

[Menus]
    main = [
        {Name = "mail@mattkjones.net", URL = "mailto:mail@mattkjones.net", weight = 1},
        {Name = "+1 404-465-1489", URL = "tel:+14044651489", weight = 2},
        {Name = "Contact Form", URL = "/#contact", weight = 3}
    ]
